const escape = text => String(text ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const safe = text => String(text ?? '').replace(/[\r\n]/g, ' ').replace(/[|`#<>]/g, '\\$&');
export function reportMarkdown(r) {
  const a = r.application;
  return `# WebTrace Security Report\n\n## Executive Summary\n\nApplication: ${safe(a.name)}\n\n${a.counts.files} files · ${a.counts.functions} functions · ${a.counts.endpoints} endpoints · ${a.counts.findings} findings\n\n${a.scoreLabel}: ${a.exposure}/100. This is a heuristic, not CVSS or a safety certificate.\n\n## Application Overview & Technology Stack\n\n${a.technologies.map(safe).join(', ') || 'Not identified'}\n\n## Attack Surface\n\n${r.sources.length} input sources · ${r.sinks.length} sensitive sinks · ${r.routes.length} route candidates\n\n## API Inventory\n\n${r.apis.map(x => `- ${safe(x.method)} ${safe(x.endpoint)} — ${safe(x.file)}:${x.line}; ${safe(x.authentication)}`).join('\n') || 'None detected'}\n\n## Function Inventory\n\n${r.functions.map(f => `- ${safe(f.name)} — ${safe(f.file)}:${f.line}; ${f.calls.length} calls`).join('\n') || 'None detected'}\n\n## Call Graph Summary\n\n${r.call_graph.length} observed or resolved call edges. Inspect JSON export for complete node/edge records.\n\n## Data Flow Findings\n\n${r.flows.map(f => `- ${safe(f.id)}: ${f.trace.map(id => safe(r.graph.nodes.find(n => n.id === id)?.label || id)).join(' → ')}; confidence ${f.confidence}; ${f.sanitized ? 'recognized HTML control' : 'runtime validation required'}`).join('\n') || 'No source-to-sink paths detected'}\n\n## Secrets\n\n${r.secrets.map(s => `- ${safe(s.type)} — ${safe(s.file)}:${s.line}; ${s.classification}; [REDACTED]`).join('\n') || 'No credential candidates detected'}\n\n## Security Findings\n\n${r.findings.map(f => `### ${f.id}: ${safe(f.title)}\n\nSeverity: ${f.severity} · Confidence: ${f.confidence} · Status: ${f.status}\n\nLocation: ${safe(f.file)}:${f.line}\n\n${safe(f.explanation)}\n\nEvidence:\n\n\`\`\`text\n${(f.evidence || '').replace(/\`/g, 'ˋ')}\n\`\`\`\n\nValidation: ${safe(f.validation)}\n\nRemediation: ${safe(f.recommendation)}\n`).join('\n') || 'No correlated findings. This does not establish safety.'}\n\n## Risk Summary\n\n${safe(a.scoring)}\n\n## Manual Validation Recommendations\n\n${r.recommendations.map(x => '- ' + safe(x)).join('\n')}\n\n## Limitations\n\n${r.limitations.map(x => '- ' + safe(x)).join('\n')}\n\n## Coverage Warnings\n\n${r.warnings.map(x => '- ' + safe(x)).join('\n') || 'None'}\n`;
}
export function downloadReport(report, type) {
  const markdown = type === 'json' ? null : reportMarkdown(report);
  const contents = type === 'json' ? JSON.stringify(report, null, 2) : type === 'html' ? `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>WebTrace report</title><style>body{max-width:1000px;margin:50px auto;padding:24px;background:#101818;color:#dce5e3;font:15px/1.7 monospace}pre{white-space:pre-wrap;overflow-wrap:anywhere}</style><body><pre>${escape(markdown)}</pre></body></html>` : markdown;
  const blob = new Blob([contents], { type: type === 'json' ? 'application/json' : type === 'html' ? 'text/html' : 'text/markdown' });
  const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `webtrace-report.${type === 'markdown' ? 'md' : type}`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
